// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,3,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	InStock           bool                   `protobuf:"varint,4,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *StockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockItem) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *StockItem) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

type CheckStockRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RequestedQuantity int32                  `protobuf:"varint,2,opt,name=requested_quantity,json=requestedQuantity,proto3" json:"requested_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *CheckStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CheckStockRequest) GetRequestedQuantity() int32 {
	if x != nil {
		return x.RequestedQuantity
	}
	return 0
}

type CheckStockResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Available         bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,2,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockResponse.ProtoReflect.Descriptor instead.
func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CheckStockResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckStockResponse) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *CheckStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	QuantityChange int32                  `protobuf:"varint,2,opt,name=quantity_change,json=quantityChange,proto3" json:"quantity_change,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantityChange() int32 {
	if x != nil {
		return x.QuantityChange
	}
	return 0
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewQuantity   int32                  `protobuf:"varint,2,opt,name=new_quantity,json=newQuantity,proto3" json:"new_quantity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStockResponse) GetNewQuantity() int32 {
	if x != nil {
		return x.NewQuantity
	}
	return 0
}

func (x *UpdateStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *GetStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *StockItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockResponse) GetItem() *StockItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_proto_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\"proto/inventory/v1/inventory.proto\x12\finventory.v1\"\x88\x01\n" +
	"\tStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12available_quantity\x18\x03 \x01(\x05R\x11availableQuantity\x12\x19\n" +
	"\bin_stock\x18\x04 \x01(\bR\ainStock\"a\n" +
	"\x11CheckStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12-\n" +
	"\x12requested_quantity\x18\x02 \x01(\x05R\x11requestedQuantity\"{\n" +
	"\x12CheckStockResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12-\n" +
	"\x12available_quantity\x18\x02 \x01(\x05R\x11availableQuantity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\\\n" +
	"\x12UpdateStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12'\n" +
	"\x0fquantity_change\x18\x02 \x01(\x05R\x0equantityChange\"l\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fnew_quantity\x18\x02 \x01(\x05R\vnewQuantity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"0\n" +
	"\x0fGetStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"?\n" +
	"\x10GetStockResponse\x12+\n" +
	"\x04item\x18\x01 \x01(\v2\x17.inventory.v1.StockItemR\x04item2\x82\x02\n" +
	"\x10InventoryService\x12O\n" +
	"\n" +
	"CheckStock\x12\x1f.inventory.v1.CheckStockRequest\x1a .inventory.v1.CheckStockResponse\x12R\n" +
	"\vUpdateStock\x12 .inventory.v1.UpdateStockRequest\x1a!.inventory.v1.UpdateStockResponse\x12I\n" +
	"\bGetStock\x12\x1d.inventory.v1.GetStockRequest\x1a\x1e.inventory.v1.GetStockResponseB5Z3github.com/grpc-demo/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_proto_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_v1_inventory_proto_rawDescData []byte
)

func file_proto_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_v1_inventory_proto_rawDescData
}

var file_proto_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_inventory_v1_inventory_proto_goTypes = []any{
	(*StockItem)(nil),           // 0: inventory.v1.StockItem
	(*CheckStockRequest)(nil),   // 1: inventory.v1.CheckStockRequest
	(*CheckStockResponse)(nil),  // 2: inventory.v1.CheckStockResponse
	(*UpdateStockRequest)(nil),  // 3: inventory.v1.UpdateStockRequest
	(*UpdateStockResponse)(nil), // 4: inventory.v1.UpdateStockResponse
	(*GetStockRequest)(nil),     // 5: inventory.v1.GetStockRequest
	(*GetStockResponse)(nil),    // 6: inventory.v1.GetStockResponse
}
var file_proto_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.GetStockResponse.item:type_name -> inventory.v1.StockItem
	1, // 1: inventory.v1.InventoryService.CheckStock:input_type -> inventory.v1.CheckStockRequest
	3, // 2: inventory.v1.InventoryService.UpdateStock:input_type -> inventory.v1.UpdateStockRequest
	5, // 3: inventory.v1.InventoryService.GetStock:input_type -> inventory.v1.GetStockRequest
	2, // 4: inventory.v1.InventoryService.CheckStock:output_type -> inventory.v1.CheckStockResponse
	4, // 5: inventory.v1.InventoryService.UpdateStock:output_type -> inventory.v1.UpdateStockResponse
	6, // 6: inventory.v1.InventoryService.GetStock:output_type -> inventory.v1.GetStockResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_inventory_v1_inventory_proto_init() }
func file_proto_inventory_v1_inventory_proto_init() {
	if File_proto_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_v1_inventory_proto = out.File
	file_proto_inventory_v1_inventory_proto_goTypes = nil
	file_proto_inventory_v1_inventory_proto_depIdxs = nil
}
